### ISSUE TITLE
Crash in compressor for larger objects? 

### ISSUE THREAD

**Issue by taylorchasewhite** [mjebrahimi/EasyCompressor#185]
I was compressing a large database file and in the process of doing a backup and receive an `IOException` (several GB) that the stream was too long. I am not entirely sure, but looking at a few [StackOverflow posts](https://stackoverflow.com/questions/39834634/failed-to-write-large-amount-of-data-to-stream), it appears this related to the use if `MemoryStream`(?).

## Desired Behavior
Don't crash when using compressor. 

## Environment
I was using LZMACompressor

https://github.com/mjebrahimi/EasyCompressor/blob/ed8db92974dc9eb51cad91f6baf067a1d2f9adf8/src/EasyCompressor.LZMA/LZMACompressor.cs#L211

```
System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at System.IO.Stream.<CopyToAsync>g__Core|27_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.IO.Strategies.BufferedFileStreamStrategy.CopyToAsyncCore(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at EasyCompressor.LZMACompressor.BaseCompressAsync(Stream inputStream, Stream outputStream, CancellationToken cancellationToken) in /_/src/EasyCompressor.LZMA/LZMACompressor.cs:line 208
```

**Comment by taylorchasewhite** [comment]
It looks like for this LZMA call we may be able to avoid using the MemoryStream, but for what it's worth, I'm switching over to your BrotliCompressor as you advised on the previous issue. Will see if that works for me, since it's not using a MemoryStream.

**Comment by mjebrahimi** [comment]
Hi @taylorchasewhite 
Sorry for my late response.
That bug was fixed and many improvements were added including performance optimizations.
Also, a great [benchmark](https://github.com/mjebrahimi/EasyCompressor#benchmarks) between different compression algorithms was added.
You can safely use anyone you want.

**Comment by taylorchasewhite** [comment]
Great to hear--thanks! The benchmarks page is very nice--thanks for adding.
